### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by vangelif** [zunairkhan811/Awesome-Books-ES6#2]
you have done a great job following best practices and the instructions, however there are certain things you need to review:

1. The entry point should named as index.js and index.css instead of main.js and style.css
2. Perhaps a different approach of re-structuring your whole codebase: for example place methods to the class and use that within your code. Making your code more efficient.

**Comment by vangelif** [comment]
if you implemented the changes, you can close the issue

**Comment by zunairkhan811** [comment]
Thanks Vangelis, the suggestions asked by you has been implemented, so closing this issue
https://github.com/zunairkhan811/Awesome-Books-ES6
